name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["dev"]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx bun install
          && npx bun run lint:fix

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx bun install
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npx bun install
          && npx bun run build
